//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISO815_Inventario.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class asiento_contable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public asiento_contable()
        {
            this.estado = 1;
        }

        public int id { get; set; }

        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [Display(Name = "Descripcion")]
        public string descripcion { get; set; }

        [Display(Name = "Tipo Inventario")]
        public int tipo_inventario_id { get; set; }

        [Display(Name = "Cuenta Contable")]
        public int cuenta_contable { get; set; }

        [Display(Name = "Tipo Movimiento")]
        public string tipo_movimiento { get; set; }

        [Display(Name = "Monto")]
        public decimal monto { get; set; }

        [Display(Name = "Fecha")]
        public System.DateTime fecha { get; set; }

        [Display(Name = "Estado")]
        public int estado { get; set; }
    
        public virtual tipo_inventario tipo_inventario { get; set; }
    }
}
