//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISO815_Inventario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISO815_INVEntities : DbContext
    {
        public ISO815_INVEntities()
            : base("name=ISO815_INVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<almacen> almacens { get; set; }
        public virtual DbSet<articulo> articuloes { get; set; }
        public virtual DbSet<asiento_contable> asiento_contable { get; set; }
        public virtual DbSet<tipo_inventario> tipo_inventario { get; set; }
        public virtual DbSet<transaccion> transaccions { get; set; }
    }
}
